KNOWN_EVENTS = [
    "Accounting Sync",
    "Billing Intent Claimed",
    "Billing Intent Created",
    "Billing Intent Failed",
    "Billing Intent Recovered",
    "Billing Intent Refreshed",
    "Billing Intent Reserved",
    "Company Created",
    "Company Switched",
    "Company Updated",
    "Dashboard Viewed",
    "Delete",
    "Download",
    "Download-Inv",
    "Duplicate Phone Attempt",
    "Entity Created",
    "Export",
    "Integration status",
    "Invoice Bulk Edited",
    "Invoice Created",
    "Login",
    "logout",
    "Mapping Completed",
    "Phone OTP Failed",
    "Phone OTP Resent",
    "Phone OTP Sent",
    "Phone OTP Verification Attempted",
    "Phone Verification Completed",
    "Phone Verification Locked",
    "Phone Verification Required",
    "Preview",
    "Product Subscription",
    "Recon Processed",
    "Saved Template Loaded",
    "Sign Up",
    "Transaction Configuration Edited",
    "Transaction Ledger Updated",
    "Transaction Status",
    "Transaction Type Updated",
    "Upload",
    "Vendor Mismatch Resolved",
    "Widget Clicked",
]
